# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('SEM', 'Seminar'), ('SOC', 'Social'), ('PAR', 'Party'), ('CON', 'Conference'), ('MTG', 'Meeting')], default='SOC', max_length=3)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rsvp', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
