# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='', max_length=30)),
                ('event_date', models.CharField(default='', max_length=30)),
                ('event_time', models.CharField(default='', max_length=15)),
                ('event_location', models.CharField(default='', max_length=30)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('EDU', 'Educational'), ('ART', 'Arts & Crafts'), ('SOC', 'Social'), ('LAT', 'Late Night')], default='SOC', max_length=3)),
            ],
        ),
    ]
