# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_event_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reader',
            field=models.CharField(default='', max_length=50),
        ),
    ]
